from .comments import api
from flask_restx import fields


position_field = api.model(
    "Position",
    {
        "x": fields.Float(
            required=True,
            description="The x position of comment generated by dimension reduction algorithm",
        ),
        "y": fields.Float(
            required=True,
            description="The y position of comment generated by dimension reduction algorithm",
        ),
    },
)

classification_field = api.model(
    "Classification",
    {
        "toxic": fields.Boolean(
            required=True, description="Is the comment classified as toxic?"
        ),
        "severeToxic": fields.Boolean(
            required=True, description="Is the comment classified as severeToxic?"
        ),
        "obscene": fields.Boolean(
            required=True, description="Is the comment classified as obscene?"
        ),
        "threat": fields.Boolean(
            required=True, description="Is the comment classified as threat?"
        ),
        "insult": fields.Boolean(
            required=True, description="Is the comment classified as insult?"
        ),
        "identityHate": fields.Boolean(
            required=True, description="Is the comment classified as identityHate?"
        ),
    },
)

comment_model = api.model(
    "Comment",
    {
        "comment": fields.String(
            required=True, description="The actual text that was classified"
        ),
        "position": fields.Nested(position_field),
        "classification": fields.Nested(classification_field),
    },
)
