version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod
    restart: unless-stopped
    command: "gunicorn -b 0.0.0.0:8081 --timeout 1000 app:app"
    environment:
      - ENV=production
      - API_URL=/api
    expose:
      - 8081

  frontend:
    build:
      context: ./frontend
      target: prod
    restart: unless-stopped
    environment:
      - ENV=production
      - API_URL=/api
    ports:
      - "8080:8080"
