version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod
    command: "python app.py"
    environment:
      - ENV=production
    expose:
      - 8081

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "8080:8080"
