version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - './backend:/app'
    environment:
      - ENV=development
    ports:
      - 8081:8081
    expose:
      - 8081

  frontend:
    build: 
      context: ./frontend
      target: dev
    volumes: 
      - './frontend/app/:/app'
    ports:
      - "8080:8080"
    command: "npm run serve"
