version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: base
    restart: unless-stopped
    command: "python app.py"
    volumes:
      - "./backend:/app"
    environment:
      - ENV=development
    ports:
      - 8081:8081
    expose:
      - 8081

  frontend:
    build:
      context: ./frontend
      target: dev
    restart: unless-stopped
    volumes:
      - "./frontend/app/:/app"
    ports:
      - "8080:8080"
    command: "npm run dev"
