version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod
    restart: unless-stopped
    command: "python app.py"
    stop_signal: SIGINT
    environment:
      - ENV=production
    expose:
      - 8081

  frontend:
    build:
      context: ./frontend
      target: prod
    restart: unless-stopped
    ports:
      - "8080:8080"
