from flask_restx import Namespace, fields
from ...data.data_loader import data_loader

dataset_api = Namespace(
    "datasets", description="All operations regarding available datasets"
)

position_field = dataset_api.model(
    "Position",
    {
        "x": fields.Float(
            required=True,
            description="The x position of comment generated by dimension reduction algorithm",
        ),
        "y": fields.Float(
            required=True,
            description="The y position of comment generated by dimension reduction algorithm",
        ),
    },
)

class_field = dataset_api.model(
    "Class",
    {
        "assigned": fields.Boolean(
            required=True, description="Was the comment classified in this class?"
        ),
        "prediction": fields.Float(
            required=True, description="Prediction given from model in %"
        ),
    },
)

classification_field = dataset_api.model(
    "Classification",
    {
        "toxic": fields.Nested(class_field),
        "severeToxic": fields.Nested(class_field),
        "obscene": fields.Nested(class_field),
        "threat": fields.Nested(class_field),
        "insult": fields.Nested(class_field),
        "identityHate": fields.Nested(class_field),
    },
)

data_point_model = dataset_api.model(
    "DataPoint",
    {
        "text": fields.String(
            required=True, description="The actual text that was classified"
        ),
        "position": fields.Nested(position_field),
        "classification": fields.Nested(classification_field),
    },
)

dataset_model = dataset_api.model(
    "Dataset",
    {
        "name": fields.String(required=True, description="Name of the dataset"),
        "samplesCount": fields.Integer(
            allow_null=True,
            description="Total number of samples in the dataset, If dataset isn't loaded will be null",
        ),
        "availableReductionModels": fields.List(
            fields.String,
            description="List of available reduction models for given dataset",
        ),
    },
)

dataset_load_input = dataset_api.model(
    "DatasetLoadInput",
    {
        "datasetName": fields.String(
            required=True,
            description=f"Name of dataset to load from: {data_loader.get_dataset_names()}",
        ),
        "availableReductionModel": fields.String(
            description="Name of the algorithm from /datasets endpoint which was used to reduce data dimension. If empty all of the reduction models will be loaded",
        ),
    },
)

dataset_load_response = dataset_api.model(
    "DatasetLoadResponse",
    {
        "datasetDetails": fields.Nested(dataset_model),
        "status": fields.String(
            description="'partial' if only given reduction model loaded 'all' if all models loaded"
        ),
    },
)
